Controllers/BodyController.cs
using MangaStore.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MangaStore.Controllers
{
    public class BodyController : Controller
    {
        DataMangaDataContext data = new DataMangaDataContext();
        private List<TRUYEN> Laytruyenmoi(int count)
        {
            return data.TRUYENs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        // GET: Body
        public ActionResult Index(int? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);
            var truyenmoi = Laytruyenmoi(22);   
            return View(truyenmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Banchay()
        {
            var banchay = from bc in data.BanChays select bc;
            return PartialView(banchay);
        }
        public ActionResult Banchaytheo(int id, int? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);
            var truyen = from t in data.TRUYENs
                         join bc in data.IDBanChays on t.MaTruyen equals bc.MaTruyen
                         where bc.MaBanChay == id   
                         select t;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Noibat()
        {
            var noibat = from nb in data.NoiBats select nb;
            return PartialView(noibat);
        }
        public ActionResult Noibattheo(int id, int? page)
        {
            int pageSize = 12;
            int pageNum = (page ?? 1);
            var truyen = from b  in data.TRUYENs
                         join nb in data.IDNoiBats on b.MaTruyen equals nb.MaTruyen
                         where nb.MaNoiBat == id
                         select b;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Chitiettruyen(int id)
        {
            var truyen= from s in data.TRUYENs where s.MaTruyen == id select s;
            return View(truyen.Single());
        }
    }
}

Controllers/KindController.cs
using MangaStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MangaStore.Controllers
{
    public class KindController : Controller
    {
        DataMangaDataContext data = new DataMangaDataContext();
        // GET: Kind
        private List<TRUYEN> Laytruyenmoi(int count)
        {
            return data.TRUYENs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyenmoi = Laytruyenmoi(20);
            return View(truyenmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Theloai()
        {
            var theloai = from tl in data.THELOAIs select tl;
            return PartialView(theloai);
        }
        public ActionResult Truyentheotheloai(int id,int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from t in data.TRUYENs
                         join tl in data.MACOMICs on t.MaTruyen equals tl.MaTruyen
                         where tl.MaTL == id
                         select t;
            return View(truyen.ToPagedList(pageNum, pageSize));

        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult TruyentheoNXB(int id, int? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from n in data.TRUYENs
                          join nxb in data.MAQUANHEs on n.MaTruyen equals nxb.MaTruyen
                          where nxb.MaNXB == id
                          select n;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Gia()
        {
            var gia = from g in data.GIás select g;
            return PartialView(gia);
        }
        public ActionResult TruyentheoGiaTri(int id, int? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from gt in data.TRUYENs
                          join g in data.GiaTruyens on gt.MaTruyen equals g.MaTruyen
                          where g.MaGia == id
                          select gt;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Search(String a)
        {
            var truyen = data.TRUYENs.Where(s => s.TenTruyen.Contains(a)).ToList();
            return View(truyen);
        }
        public ActionResult Chitiettruyen(int id)
        {
            var truyen = from s in data.TRUYENs where s.MaTruyen == id select s;
            return View(truyen.Single());
        }
    }   
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/assets/Logo2.ico">
    <link rel="icon" href="~/assets/Logo2.ico" />
    <meta name="viewport" content="width=device-width" />
    <title>Admin</title>
    <link href="~/assets/css/admin2.css" rel="stylesheet" />
    <link href="~/assets/css/admin1.css" rel="stylesheet" />

</head>
<body id="page-top">
    <div id="wrapper" style="background-color: aliceblue ">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar" style="line-height: 2;">
            <li class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html"></li>
            <li class="sidebar-brand-icon rotate-n-15">
            </li>

            <li class="sidebar-divider my-0">
            <li class="sidebar-divider">
                <div class="sidebar-heading" style="color: white;font-size: initial;">
                    Tài Khoản
                </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index", "Taikhoan")">
                    <span>Quản Lí Tài Khoản</span>
                </a>
            </li>
            <li class="sidebar-heading" style="color: white;font-size: initial;">
                __________________
            </li>
            <li class="sidebar-divider">
                <div class="sidebar-heading" style="color: white;font-size: initial;">
                    Chức Năng
                </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index", "Theloai")">
                    <span>Quản Lí Thể Loại</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Nhaxuatban")">
                    <span>Quản Lí Nhà Xuất Bản</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Truyen", "Admin")">
                    <span>Quản Lí Truyện</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index", "Truyentheotheloai")">
                    <span>Xếp Truyện Theo Thể Loại</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Truyentheonhaxuatban")">
                    <span>Xếp Truyện Theo Nhà Xuất Bản </span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Truyentheogiatien")">
                    <span>Xếp Truyện Theo Giá Tiền</span>
                </a>
            </li>
            <li class="sidebar-heading" style="color: white;font-size: initial;">
                __________________
            </li>
            <li class="sidebar-divider">
                <div class="sidebar-heading" style="color: white;font-size: initial;">
                    Tình Trạng
                </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index", "Truyenbanchay")">
                    <span>Truyện Bán Chạy</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Truyennoibat")">
                    <span>Truyện Nổi Bật</span>
                </a>
            </li>


        </ul>
        @RenderBody()
    </div>

</body>

</html>

Views/Shared/_LayoutBody1.cshtml
@model IEnumerable<MangaStore.Models.TRUYEN>
<div class="bg-gray-200 space-2 space-lg-3" id="truyen-ban-chay">
    <div class="container ">
        <div class="d-md-flex justify-content-between">
            <header class="mb-4">
                <h2 class="font-size-7" style="color: cornflowerblue;">Truyện Bán Chạy</h2>
            </header>
            <select class="js-select selectpicker dropdown-select orderby" name="orderby" data-style="border-bottom shadow-none outline-none py-2" style="border: #ffffff">
                <option value="#" selected="selected">Bán Chạy</option>
                <option value="/Body/Banchaytheo/1">Bán Chạy Theo Tuần</option>
                <option value="/Body/Banchaytheo/2">Bán Chạy Theo Tháng</option>
                <option value="/Body/Banchaytheo/3">Bán Chạy Theo Năm</option>
            </select>
            <script>
                window.addEventListener('load', () => {
                    $('#truyen-ban-chay select[name="orderby"]').change(e => {
                        e.preventDefault();
                        $.ajax({
                            url: e.target.value,
                            dataType: 'html',
                            success: raw => {
                                const body = $(document.createElement('div').outerHTML).html(raw).find('#truyen-ban-chay .products').html();
                                $('#truyen-ban-chay .products').html(body);
                            },
                        });
                    });
                });
            </script>
        </div>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="example1" role="tabpanel" aria-labelledby="example1-tab">
                <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-wd-6 border-top border-left my-0">
                    @foreach (var truyen in Model)
                    {
                        <li class="product col">
                            <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                                <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                                    <div class="woocommerce-loop-product__thumbnail">
                                        <a href="@Url.Action("Chitiettruyen", "Body", new { id = truyen.MaTruyen })" class="d-block"><img src="~/assets/img/ImagesBody/@truyen.Anhbia" style="height: 244px;" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyen.Mota"></a>

                                    </div>
                                    <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                        <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyen.TenTruyen</span> </h2>
                                        <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                            <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyen.Giaban</span>đ
                                        </div>
                                    </div>
                                    <div class="product__hover d-flex align-items-center">
                                        <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MUA NGAY">
                                            <span class="product__add-to-cart">MUA NGAY</span>
                                            <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                        </a>
                                        <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                            <i class="flaticon-heart"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Shared/_LayoutBody2.cshtml
@model IEnumerable<MangaStore.Models.TRUYEN>
<section class="space-bottom-3">
    <div class="banner mb-5">
        <div class="container">
            <header class="mb-5">
                <h2 class="font-size-7 font-weight-medium" style="color: cornflowerblue;">Truyện Mới Cập Nhật</h2>
            </header>
            <div class="bg-indigo-light px-xl-11 px-3 px-md-6 px-lg-5 py-6 py-xl-8 rounded-0">
                <div class="media d-block d-lg-flex">
                    <div class="media-body align-self-center mb-4 mb-lg-0">
                        <p class="banner__pretitle text-uppercase text-gray-400 font-weight-bold">MANGA WORLD</p>
                        <h2 class="hero__title font-size-10 mb-4">
                            <span class="hero__title-line-1 font-weight-regular d-block mb-1">Thông Tin Truyện Mới </span>
                        </h2>
                        <a href="" class="banner_btn rounded-0 btn btn-wide btn-primary-indigo text-white">Tại Đây &#8595;</a>
                    </div>
                    <img src="~/assets/img/bg1.png" class="img-fluid" alt="image-description">
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="js-slick-carousel products no-gutters border-top border-left border-right" data-pagi-classes="text-center position-absolute right-0 left-0 u-slick__pagination mt-4 mb-0" data-arrows-classes="d-none u-slick__arrow u-slick__arrow-centered--y" data-arrow-left-classes="fas fa-chevron-left u-slick__arrow-inner u-slick__arrow-inner--left ml-lg-n10" data-arrow-right-classes="fas fa-chevron-right u-slick__arrow-inner u-slick__arrow-inner--right mr-lg-n10" data-slides-show="5" data-responsive='[{
                   "breakpoint": 1500,
                   "settings": {
                     "slidesToShow": 4
                   }
                },{
                   "breakpoint": 1199,
                   "settings": {
                     "slidesToShow": 3
                   }
                },{
                   "breakpoint": 992,
                   "settings": {
                     "slidesToShow": 2
                   }
                }, {
                   "breakpoint": 768,
                   "settings": {
                     "slidesToShow": 1
                   }
                }, {
                   "breakpoint": 554,
                   "settings": {
                     "slidesToShow": 1
                   }
                }]'>
            @foreach (var truyen in Model.OrderBy(x => x.Ngaycapnhat).Reverse())
            {
                <div class="product">
                    <div class="product__inner overflow-hidden p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail"style="height: 320px;">
                                <a href="@Url.Action("Chitiettruyen", "Body", new { id = truyen.MaTruyen })" class="d-block"><img src="~/assets/img/ImagesBody/@truyen.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyen.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyen.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto">
                                    <span class="product__add-to-cart">MUA NGAY</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
            </div>
    </div>
</section>

Views/Shared/_LayoutBody3.cshtml
@model IEnumerable<MangaStore.Models.TRUYEN>
<div class="bg-gray-200 space-2 space-lg-3" id="truyen-noi-bat">
    <div class="container ">
        <div class="d-md-flex justify-content-between">
            <header class="mb-4">
                <h2 class="font-size-7" style="color: cornflowerblue;">Truyện Nổi Bật</h2>
            </header>
            <select class="js-select selectpicker dropdown-select orderby" name="orderby" data-style="border-bottom shadow-none outline-none py-2" style="border: #ffffff">
                <option value="#" selected="selected">Nổi Bật</option>
                <option value="/Body/Noibattheo/1">Nổi Bật Theo Tuần</option>
                <option value="/Body/Noibattheo/2">Nổi Bật Theo Tháng</option>
                <option value="/Body/Noibattheo/3">Nổi Bật Theo Năm</option>
            </select>
            <script>
                window.addEventListener('load', () => {
                    $('#truyen-noi-bat select[name="orderby"]').change(e => {
                        e.preventDefault();
                        $.ajax({
                            url: e.target.value,
                            dataType: 'html',
                            success: raw => {
                                const body = $(document.createElement('div').outerHTML).html(raw).find('#truyen-noi-bat .products').html();
                                $('#truyen-noi-bat .products').html(body);
                            },
                        });
                    });
                });
            </script>
        </div>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="example1" role="tabpanel" aria-labelledby="example1-tab">
                <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-wd-6 border-top border-left my-0">
                    @foreach (var truyen in Model)
                    {
                        <li class="product col">
                            <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                                <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                                    <div class="woocommerce-loop-product__thumbnail">
                                        <a href="@Url.Action("Chitiettruyen", "Body", new { id = truyen.MaTruyen })" class="d-block"><img src="~/assets/img/ImagesBody/@truyen.Anhbia" style="height: 244px;" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyen.Mota"></a>

                                    </div>
                                    <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                        <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyen.TenTruyen</span> </h2>
                                        <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                            <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyen.Giaban</span>đ
                                        </div>
                                    </div>
                                    <div class="product__hover d-flex align-items-center">
                                        <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MUA NGAY">
                                            <span class="product__add-to-cart">MUA NGAY</span>
                                            <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                        </a>
                                        <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyen.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                            <i class="flaticon-heart"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Shared/_LayoutGioHang.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Mua Hàng | Manga World</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="shortcut icon" href="~/assets/Logo2.ico">
    <link rel="icon" href="~/assets/Logo2.ico" />

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../../assets/vendor/font-awesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="../../assets/vendor/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="../../assets/vendor/animate.css/animate.css">
    <link rel="stylesheet" href="../../assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="../../assets/vendor/slick-carousel/slick/slick.css" />
    <link rel="stylesheet" href="../../assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">

    <link rel="stylesheet" href="../../assets/css/theme.css">
</head>
<body>
    @RenderBody()
    <footer class="site-footer_v7">
        <div class="space-1 space-lg-3 bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-lg-4">
                        <div class="mb-5 mb-lg-0">
                            <h4 class="font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-gray-500">Thông Tin</h4>
                            <address class="font-size-2 mb-5">
                                <span class="mb-2 font-weight-normal text-white">
                                    497 Phan Van Tri , Go Vap  <br> VietNam
                                </span>
                            </address>
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class="mb-5 mb-lg-0">
                            <h4 class="font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-gray-500">Liên Hệ</h4>
                            <div class="mb-4">
                                <a href="https://myaccount.google.com/?hl=vi&utm_source=OGB&utm_medium=act" class="font-size-2 d-block mb-1 text-white">hoangdanghuy222@gmail.com</a>
                                <a href="tel:0836841560" class="font-size-2 d-block text-white">
                                    0836841560
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-lg-4">
                        <div class="mb-5 mb-lg-0">
                            <h4 class="font-size-3 font-weight-medium mb-2 mb-xl-5 pb-xl-1 text-gray-500">Theo Dõi</h4>
                            <ul class="list-unstyled mb-0 d-flex">
                                <li class="btn pl-0">
                                    <a class="text-white" href="https://www.instagram.com/_emoghl/">
                                        <span class="fab fa-instagram"></span>
                                    </a>
                                </li>
                                <li class="btn">
                                    <a class="text-white" href="https://www.facebook.com/huydang2805/">
                                        <span class="fab fa-facebook-f"></span>
                                    </a>
                                </li>
                                <li class="btn">
                                    <a class="text-white" href="https://twitter.com/Zen_Habuto">
                                        <span class="fab fa-twitter"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-3 bg-black">
            <div class="container py-1">
                <div class="d-md-flex text-center text-md-left justify-content-between align-items-center">

                    <p class="mb-3 mb-lg-0 font-size-2 text-gray-500">©2022 MangaWorld . Thiên Đường Truyện Tranh</p>

                    <div class="d-md-flex justify-content-md-end align-items-center">

                        <select class="js-select selectpicker dropdown-select" data-style="bg-transparent border-0 text-gray-500 px-4 py-2 rounded-0 height-5 outline-none shadow-none form-control font-size-2" data-dropdown-align-right="true">
                            <option value="one" selected>Hoàng Đăng Huy (Nhóm 7)</option>
                            <option value="two">Vũ Luân</option>
                            <option value="three">Công Minh</option>
                            <option value="four">Phạm Vũ</option>
                        </select>

                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

Views/Shared/_Layoutxndh.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Xác Nhận Đơn Hàng | Manga World</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="shortcut icon" href="~/assets/Logo2.ico">
    <link rel="icon" href="~/assets/Logo2.ico" />

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="../../assets/vendor/font-awesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="../../assets/vendor/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="../../assets/vendor/animate.css/animate.css">
    <link rel="stylesheet" href="../../assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="../../assets/vendor/slick-carousel/slick/slick.css" />
    <link rel="stylesheet" href="../../assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">

    <link rel="stylesheet" href="../../assets/css/theme.css">
</head>
<body>
    <div class="page-header border-bottom">
        <div class="container">
            <div class="d-md-flex justify-content-between align-items-center py-4">
                <h1 class="page-title font-size-3 font-weight-medium m-0 text-lh-lg">Xác Nhận Đơn Hàng </h1>
                <nav class="woocommerce-breadcrumb font-size-2">
                    <a href="/Kind/Index" class="h-primary">Thể Loại</a>
                    <span class="breadcrumb-separator mx-1"><i class="fas fa-angle-right"></i></span>
                    <a href="/GioHang/Giohang" class="h-primary">Giỏ Hàng</a>
                    <span class="breadcrumb-separator mx-1"><i class="fas fa-angle-right"></i></span>Xác Nhận Đơn Hàng 
                </nav>
            </div>
        </div>
    </div>

    @RenderBody()
</body>

</html>