Controllers/KindController.cs
using MangaStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MangaStore.Controllers
{
    public class KindController : Controller
    {
        DataMangaDataContext data = new DataMangaDataContext();
        // GET: Kind
        private List<TRUYEN> Laytruyenmoi(int count)
        {
            return data.TRUYENs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyenmoi = Laytruyenmoi(20);
            return View(truyenmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Theloai()
        {
            var theloai = from tl in data.THELOAIs select tl;
            return PartialView(theloai);
        }
        public ActionResult Truyentheotheloai(int id,int ? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from t in data.TRUYENs
                         join tl in data.MACOMICs on t.MaTruyen equals tl.MaTruyen
                         where tl.MaTL == id
                         select t;
            return View(truyen.ToPagedList(pageNum, pageSize));

        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult TruyentheoNXB(int id, int? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from n in data.TRUYENs
                          join nxb in data.MAQUANHEs on n.MaTruyen equals nxb.MaTruyen
                          where nxb.MaNXB == id
                          select n;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Gia()
        {
            var gia = from g in data.GIás select g;
            return PartialView(gia);
        }
        public ActionResult TruyentheoGiaTri(int id, int? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            var truyen = from gt in data.TRUYENs
                          join g in data.GiaTruyens on gt.MaTruyen equals g.MaTruyen
                          where g.MaGia == id
                          select gt;
            return View(truyen.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Search(String a)
        {
            var truyen = data.TRUYENs.Where(s => s.TenTruyen.Contains(a)).ToList();
            return View(truyen);
        }
        public ActionResult Chitiettruyen(int id)
        {
            var truyen = from s in data.TRUYENs where s.MaTruyen == id select s;
            return View(truyen.Single());
        }
    }   
}

Controllers/NhaxuatbanController.cs
using MangaStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MangaStore.Controllers
{
    public class NhaxuatbanController : Controller
    {
        DataMangaDataContext db = new DataMangaDataContext();
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View(db.NHAXUATBANs.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View();
        }
        [HttpPost]
        public ActionResult Create(NHAXUATBAN nhaxuatban)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                db.NHAXUATBANs.InsertOnSubmit(nhaxuatban);
                db.SubmitChanges();

                return RedirectToAction("Index", "Nhaxuatban");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var nhaxuatban = from nxb in db.NHAXUATBANs where nxb.MaNXB == id select nxb;
                return View(nhaxuatban.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                NHAXUATBAN nhaxuatban = db.NHAXUATBANs.SingleOrDefault(n => n.MaNXB == id);
                db.NHAXUATBANs.DeleteOnSubmit(nhaxuatban);
                db.SubmitChanges();

                return RedirectToAction("Index", "Nhaxuatban");
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var nhaxuatban = from nxb in db.NHAXUATBANs where nxb.MaNXB == id select nxb;
                return View(nhaxuatban.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Capnhat(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                NHAXUATBAN nhaxuatban = db.NHAXUATBANs.SingleOrDefault(n => n.MaNXB == id);

                UpdateModel(nhaxuatban);
                db.SubmitChanges();
                return RedirectToAction("Index", "Nhaxuatban");
            }
        }
    }
}

Controllers/TheloaiController.cs
using MangaStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MangaStore.Controllers
{
    public class TheloaiController : Controller
    {
        DataMangaDataContext db = new DataMangaDataContext();
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View(db.THELOAIs.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View();
        }
        [HttpPost]
        public ActionResult Create(THELOAI theloai)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                db.THELOAIs.InsertOnSubmit(theloai);
                db.SubmitChanges();

                return RedirectToAction("Index", "Theloai");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var theloai = from tl in db.THELOAIs where tl.MaTL == id select tl;
                return View(theloai.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                THELOAI theloai = db.THELOAIs.SingleOrDefault(n => n.MaTL == id);
                db.THELOAIs.DeleteOnSubmit(theloai);
                db.SubmitChanges();

                return RedirectToAction("Index", "Theloai");
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var theloai = from tl in db.THELOAIs where tl.MaTL == id select tl;
                return View(theloai.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Capnhat(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                THELOAI theloai = db.THELOAIs.SingleOrDefault(n => n.MaTL == id);

                UpdateModel(theloai);
                db.SubmitChanges();
                return RedirectToAction("Index", "Theloai");
            }
        }
    }
}

Controllers/TruyentheotheloaiController.cs
using MangaStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MangaStore.Controllers
{
    public class TruyentheotheloaiController : Controller
    {
        DataMangaDataContext db = new DataMangaDataContext();
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View(db.MACOMICs.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View();
        }
        [HttpPost]
        public ActionResult Create(MACOMIC truyentheotheloai)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                db.MACOMICs.InsertOnSubmit(truyentheotheloai);
                db.SubmitChanges();

                return RedirectToAction("Index", "Truyentheotheloai");
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var truyentheotheloai = from tttl in db.MACOMICs where tttl.MC == id select tttl;
                return View(truyentheotheloai.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                MACOMIC truyentheotheloai = db.MACOMICs.SingleOrDefault(n => n.MC == id);
                db.MACOMICs.DeleteOnSubmit(truyentheotheloai);
                db.SubmitChanges();

                return RedirectToAction("Index", "Truyentheotheloai");
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var truyentheotheloai = from tttl in db.MACOMICs where tttl.MC == id select tttl;
                return View(truyentheotheloai.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Capnhat(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                MACOMIC truyentheotheloai = db.MACOMICs.SingleOrDefault(n => n.MC == id);

                UpdateModel(truyentheotheloai);
                db.SubmitChanges();
                return RedirectToAction("Index", "Truyentheotheloai");
            }
        }
    }
}

Views/Kind/Gia.cshtml
@model  IEnumerable<MangaStore.Models.GIá>
<p class="widget-title mb-0 font-weight-medium font-size-3 " style="
    line-height: 4;">Giá</p>
<div class=" list-group" style="font-size: 17px;line-height: 2;">
    @foreach (var item in Model)
    {
    <a href="@Url.Action("TruyentheoGiaTri", "Kind",new { id = item.MaGia })" class="list-item">
        <input type=checkbox /> @item.GiaTri
    </a>
    }
</div>

Views/Kind/Index.cshtml
@using MangaStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<TRUYEN>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutKind.cshtml";
}
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
            @foreach (var truyens in Model)
            {
                <li class="product col">
                    <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail">
                                <a href="@Url.Action("Chitiettruyen", "Kind", new { id = truyens.MaTruyen })" class="d-block" style="height: 310px;width: 192px;"><img src="~/assets/img/ImagesBody/@truyens.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyens.Mota"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyens.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyens.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("Themgiohang", "Giohang",new { @iMaTruyen = truyens.MaTruyen, strURL= Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MUA NGAY">
                                    <span class="product__add-to-cart">MUA NGAY</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich",new { @iMaTruyen = truyens.MaTruyen, strURL= Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
            <li class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
            </li>
        </ul>
        <style>
            .MenuTrang li {
                display: inline;
            }

            .pagination > li > a, .pagination > li > span {
                padding: 6px 24px;
                border: 1px solid #ddd;
                background-color: #ffffff;
                text-decoration: none;
                float: right;
                font-size: 25px;
            }
        </style>
    </div>
</div>

Views/Kind/Nhaxuatban.cshtml
@model  IEnumerable<MangaStore.Models.NHAXUATBAN>
<p class="widget-title mb-0 font-weight-medium font-size-3 " style="
    line-height: 4;" ;">Nhà Xuất Bản</p>
<div class=" list-group"style="font-size: 17px;line-height: 2;">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("TruyentheoNXB", "Kind",new { id = item.MaNXB})" class="list-item">
            @item.TenNXB
        </a>
    }
</div>

Views/Kind/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutKind.cshtml";
}

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
            @foreach (var truyens in Model)
            {
                <li class="product col">
                    <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail">
                                <a href="@Url.Action("Chitiettruyen", "Kind", new { id = truyens.MaTruyen })" class="d-block"><img src="~/assets/img/ImagesBody/@truyens.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyens.Mota"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyens.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyens.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="Mua Ngay">
                                    <span class="product__add-to-cart">Mua Ngay</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })    " class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

Views/Kind/Theloai.cshtml
@model  IEnumerable<MangaStore.Models.THELOAI>
    <p class="widget-title mb-0 font-weight-medium font-size-3 " style="
    line-height: 4;">Thể Loại</p>
    <div class=" list-group" style="font-size: 17px;line-height: 2;">
        @foreach (var item in Model)
        {
            <a href="@Url.Action("Truyentheotheloai", "Kind",new { id = item.MaTL})" class="list-item">
                @item.TenTL
            </a>
        }
    </div>

Views/Kind/TruyentheoGiaTri.cshtml
@using MangaStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<TRUYEN>
@{
    ViewBag.Title = "TruyentheoGiaTri";
    Layout = "~/Views/Shared/_LayoutKind.cshtml";
}

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
            @foreach (var truyens in Model)
            {
                <li class="product col">
                    <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail">
                                <a href="@Url.Action("Chitiettruyen", "Kind", new { id = truyens.MaTruyen })" class="d-block"style="height: 310px;width: 192px;"><img src="~/assets/img/ImagesBody/@truyens.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyens.Mota"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyens.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyens.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MUA NGAY">
                                    <span class="product__add-to-cart">MUA NGAY</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
            <li class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("TruyentheoGiaTri", new { page = page }))
            </li>
        </ul>
        <style>
            .MenuTrang li {
                display: inline;
            }

            .pagination > li > a, .pagination > li > span {
                padding: 6px 24px;
                border: 1px solid #ddd;
                background-color: #ffffff;
                text-decoration: none;
                float: right;
                font-size: 25px;
            }
        </style>
    </div>
</div>

Views/Kind/TruyentheoNXB.cshtml
@using MangaStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<TRUYEN>
@{
    ViewBag.Title = "TruyentheoNXB";
    Layout = "~/Views/Shared/_LayoutKind.cshtml";
}
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
            @foreach (var truyens in Model)
            {
                <li class="product col">
                    <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail">
                                <a href="@Url.Action("Chitiettruyen", "Kind", new { id = truyens.MaTruyen })" class="d-block"style="height: 310px;width: 192px;"><img src="~/assets/img/ImagesBody/@truyens.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyens.Mota"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyens.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyens.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MUA NGAY">
                                    <span class="product__add-to-cart">MUA NGAY</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
            <li class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("TruyentheoNXB", new { page = page }))
            </li>
        </ul>
        <style>
            .MenuTrang li {
                display: inline;
            }

            .pagination > li > a, .pagination > li > span {
                padding: 6px 24px;
                border: 1px solid #ddd;
                background-color: #ffffff;
                text-decoration: none;
                float: right;
                font-size: 25px;
            }
            
        </style>
    </div>
</div>

Views/Kind/Truyentheotheloai.cshtml
@using MangaStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<TRUYEN>
@{
    ViewBag.Title = "Truyentheotheloai";
    Layout = "~/Views/Shared/_LayoutKind.cshtml";
}

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
            @foreach (var truyens in Model)
            {
                <li class="product col">
                    <div class="product__inner overflow-hidden bg-white p-3 p-md-4d875">
                        <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                            <div class="woocommerce-loop-product__thumbnail">
                                <a href="@Url.Action("Chitiettruyen", "Kind", new { id = truyens.MaTruyen })" class="d-block"style="height: 310px;width: 192px;"><img src="~/assets/img/ImagesBody/@truyens.Anhbia" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description" title="@truyens.Mota"></a>
                            </div>
                            <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><span>@truyens.TenTruyen</span> </h2>
                                <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                    <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol"></span>@truyens.Giaban</span>đ
                                </div>
                            </div>
                            <div class="product__hover d-flex align-items-center">
                                <a href="@Url.Action("ThemGiohang", "GioHang", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="MuaNgay">
                                    <span class="product__add-to-cart">Mua Ngay</span>
                                    <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                </a>
                                <a href="@Url.Action("ThemTruyenThich","Thich", new { @iMaTruyen = truyens.MaTruyen, @strURL = Request.Url.ToString() })" class="h-p-bg btn btn-outline-primary border-0">
                                    <i class="flaticon-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
            <li class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("Truyentheotheloai", new { page = page }))
            </li>
        </ul>
        <style>
            .MenuTrang li {
                display: inline;
            }

            .pagination > li > a, .pagination > li > span {
                padding: 6px 24px;
                border: 1px solid #ddd;
                background-color: #ffffff;
                text-decoration: none;
                float: right;
                font-size: 25px;
            }
        </style>
    </div>
</div>